age <- c("5-6", "7-8", "9-10")
photo_A <- c(18, 2, 20)
photo_B <- c(22, 28, 10)
photo_C <- c(20, 40, 40)
cov_BC <- cov(photo_B, photo_C)
pref_matrix <- cov(cbind(photo_A, photo_B, photo_C))
cor_BC <- cor(photo_B, photo_C)
cor_matrix <- cor(cbind(photo_A, photo_B, photo_C))
print("Covariance between B and C:")
print(cov_BC)
print("Covariance matrix for preferences:")
print(pref_matrix)
print("Correlation between B and C:")
print(cor_BC)
print("Correlation matrix for preferences:")
print(cor_matrix)
